nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "80:80"
web_swift_how_node:
  build: ./swift-how
  environment:
    - VIRTUAL_HOST=swift.how,evilcome.com
    - VIRTUAL_PORT=8003
  ports:
    - "8003:8003"
blog_swift_how_ghost:
  image: ghost
  environment:
    - VIRTUAL_HOST=blog.swift.how
    - VIRTUAL_PORT=8004
  ports:
    - "8004:2368"
web_evilcome_com_keystone:
  build: ./evilcome-com
  environment:
    - NODE_ENV=production
    - VIRTUAL_HOST=blog.evilcome.com
    - VIRTUAL_PORT=8005
  ports:
    - "8005:8005"
  links:
    - mongo
mongo:
  image: mongo
  ports:
    - "27017:27017"
