swifthow:
  build: ./swift-how
  volumes:
    - swift-how/app:/src/app
  environment:
    - VIRTUAL_HOST=swift.how,www.swift.how
    - VIRTUAL_PORT=8003
  ports:
    - "8003:8003"
blog:
  build: ./blog
  volumes:
    # blog content (post db)
    - blog/content/data:/usr/src/app/content/data
    # blog images
    - blog/content/images:/usr/src/app/content/images
  environment:
    - VIRTUAL_HOST=blog.swift.how
    - VIRTUAL_PORT=8001
    - NODE_ENV=production
  ports:
    - "8001:8001"
