blogswifthow:
  build: ./blog-swift-how
  volumes:
    - /root/projects/mesimers:/src
  environment:
    - VIRTUAL_HOST=blog.swift.how
    - VIRTUAL_PORT=8001
  ports:
    - "8001:2368"
swifthow:
  build: ./swift-how
  volumes:
    - swift-how/app:/src/app
  environment:
    - VIRTUAL_HOST=swift.how,www.swift.how
    - VIRTUAL_PORT=8003
  ports:
    - "8003:8003"

# blog:
#   image: ghost
#   environment:
#     - VIRTUAL_HOST=blog.swift.how
#     - VIRTUAL_PORT=8004
#   ports:
#     - "8004:2368"
