swifthow:
  build: ./swift-how
  volumes:
    - swift-how/app:/src/app
  environment:
    - VIRTUAL_HOST=swift.how,www.swift.how
    - VIRTUAL_PORT=8003
  ports:
    - "8003:8003"
blogswifthow:
  build: ./blog-swift-how
  volumes:
    # blog content (post db)
    - blog-swift-how/content/data:/usr/src/app/content/data
    # blog images
    - blog-swift-how/content/images:/usr/src/app/content/images
  environment:
    - VIRTUAL_HOST=blog.swift.how
    - VIRTUAL_PORT=8005
    - NODE_ENV=production
  ports:
    - "8005:8005"
