# blogswifthow:
#   build: ./blog-swift-how
#   volumes:
#     - blog-swift-how/mesimers:/src/app
#   environment:
#     - VIRTUAL_HOST=blog.swift.how
#     - VIRTUAL_PORT=8004
#   ports:
#     - "8004:2368"
swifthow:
  build: ./swift-how
  volumes:
    - swift-how/app:/src/app
  environment:
    - VIRTUAL_HOST=swift.how,www.swift.how
    - VIRTUAL_PORT=8003
  ports:
    - "8003:8003"
mesimers:
  build: ./mesimers
  volumes:
    # blog content
    - mesimers/content/data:/usr/src/app/content/data
    - mesimers/content/images:/usr/src/app/content/images
  environment:
    - VIRTUAL_HOST=blog.swift.how
    - VIRTUAL_PORT=8005
    - NODE_ENV=production
  ports:
    - "8005:8005"
# blog:
#   image: ghost
#   environment:
#     - VIRTUAL_HOST=blog.swift.how
#     - VIRTUAL_PORT=8004
#   ports:
#     - "8004:2368"
