nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "80:80"
nodeswifthow: 
  build: ./swift-how
  environment:
    - VIRTUAL_HOST=swift.how evilcome.com blog.swift.how
    - VIRTUAL_PORT=8003
  ports:
    - "8003:8003"
